### PR TITLE
Code & Performance improvements

### PR DESCRIPTION
**Pull request by MarcWebDev**

### CODE REVIEW

**Comment by Shadowevil015** [comment]
I am going to take a wild guess, and say that you don't play on CCNet? And you just found this project somewhere else?

**Comment by Shadowevil015** [comment]
Thanks for the PR btw

**Comment by MarcWebDev** [comment]
I found the project on github because I look for smaller projects and try to improve the code and help as much as I can

**Comment by MarcWebDev** [comment]
Why don't you merge my request?

**Review by mezotv — APPROVED** [review]
Looking good

**Pull request merged**
